config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)' do
  resources :blogs
  get 'about', to: 'static_pages#about'
  root to: 'static_pages#home'
  get 'static_pages/home'

  get 'static_pages/about'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
has_many :blogs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_i18n_locale_from_params

  protected
    def set_i18n_locale_from_params
      if params[:locale]
        if I18n.available_locales.map(&:to_s).include?(params[:locale])
          I18n.locale = params[:locale]
        else
          flash.now[:notice] =
            "#{params[:locale]} translation not available"
        end
      end
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  # GET /blogs
  def index
    @blogs = Blog.all
  end
  # GET /blogs/1
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  def create
      @blog = current_user.blogs.build(blog_params)
    if @blog.save
      redirect_to blog_path(@blog, locale:I18n.locale), notice: t(".blog_succes")
    else
      render :new
    end
  end
  # PATCH/PUT /blogs/1
  def update
    if @blog.update(blog_params)
      redirect_to blog_path(@blog, locale:I18n.locale), notice: t(".blog_updated")
    else
      render :edit
    end
  end
  # DELETE /blogs/1
  def destroy
    @blog.destroy
    redirect_to blogs_url(locale: I18n.locale), notice: t(".blog_destroyed")
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def login_helper style = ''
    if user_signed_in?
      link_to t('logout'), destroy_user_session_path(locale: I18n.locale), method: :delete , class: style
    else
      (link_to t('login'), new_user_session_path(locale: I18n.locale), class: style) + " ".html_safe +
      (link_to t('register'), new_user_registration_path(locale: I18n.locale), class: style)
    end
  end

  def nav_items
    [
      {
        url: root_path(params[:locale]),
        title: t('.home')
      },

      {
        url: about_path(params[:locale]),
        title: t('.about')
      },

    ]
  end

  def nav_helper style, tag_type
    nav_links = ''
    nav_items.each do |item|
      nav_links << "<#{tag_type}><a href='#{item[:url]}' class='#{style} #{active? item[:url]}' >#{item[:title]}</a></#{tag_type}>"
    end
    nav_links.html_safe
  end

  def active? path
    "active" if current_page? path
  end

  def alerts
    alert = (flash[:alert] || flash[:error] || flash[:notice])
    if alert
      alert_generator alert
    end
  end

  def alert_generator msg
    js add_gritter(msg, title: "Fix my name on the alert generator method in your application_helper", sticky: false)
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/blogs/_form.html.erb
<% if @blog.errors.any? %>
  <% @blog.errors.full_messages.each do |error| %>
    <li><%= alert_generator error %></li>
  <% end %>
<% end %>

    <div class="form-group">
            <%= f.label :title %>
      <%= f.text_field :title, class:"form-control" %>
      </div>

    <div class="form-group">
            <%= f.label :body %>
      <%= f.text_area :body, class:"form-control" %>
      </div>

    <div class="form-group">
            <%= f.label :user_id %>
      <%= f.text_field :user_id, class:"form-control" %>
      </div>

app/views/blogs/edit.html.erb
<h1><%= t('editing') %>  Blog</h1>
<%= form_for(@blog, url:blog_path(@blog, locale: I18n.locale) ) do |f| %>

  <%= render 'form', f:f %>

  <div class="form-group">
    <%= f.submit t('.update'), class:"btn btn-primary" %>
  </div>
  <% end %>

<%= link_to fa_icon('folder-open-o'), blog_path(@blog, locale:I18n.locale) %> |
<%= link_to fa_icon('arrow-circle-left'), blogs_path(locale:I18n.locale) %>

app/views/blogs/index.html.erb
<h2><%= t('.Blogs') %></h2>

<hr>

<div>
  <% @blogs.each do |blog| %>
    <div class="content">
      <p><%= blog.title %></p>
      <p><%= blog.body %></p>
      <p><%= blog.user %></p>
      <p><%= link_to t('show'), blog_path(blog, locale: I18n.locale) %></p>
      <p><%= link_to t('edit'), edit_blog_path(blog,locale: I18n.locale) %></p>
      <p><%= link_to t('delete'), blog_path(blog, locale: I18n.locale), method: :delete, data: { confirm: t('are_you_sure') } %></p>
    </div>
  <% end %>
</div>

<br>

<%= link_to fa_icon('plus'), new_blog_path( locale:I18n.locale) %>

app/views/blogs/new.html.erb
<h1><%= t('adding') %> Blog</h1>

<%= form_for(@blog, url:blogs_path( locale: I18n.locale) ) do |f| %>

  <%= render 'form',  f: f %>

  <div class="form-group">
    <%= f.submit t('.create'), class:'btn btn-primary' %>
  </div>
  <% end %>

<%= link_to fa_icon('arrow-circle-left'), blogs_path(locale:I18n.locale) %>

app/views/blogs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @blog.user %>
</p>

<%= link_to fa_icon('edit'), edit_blog_path(@blog, locale: I18n.locale) %> |
<%= link_to fa_icon('arrow-circle-left'), blogs_path(locale: I18n.locale) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display|Raleway" rel="stylesheet">
    <meta name="keywords" content="<%= @seo_keywords %>">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag 'favicons/favicon.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%= alerts %>
    <div class="container mt-3">
      <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse blog-nav">
  <button class="navbar-toggler navbar-toggler-right" type="button"
    data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false"
    aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="container">
    <%= link_to "HOME", root_path, class:"navbar-brand h3"%>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= nav_helper "nav-link", "li"%>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= t('languages') %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to locale: "en" do %>
              <%= content_tag :span, "English", :class => "dropdown-item" %>
            <% end %>
            <%= link_to locale: "pt" do %>
              <%= content_tag :span, "Português", :class => "dropdown-item" %>
            <% end %>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav pull-right">
        <%= login_helper "nav-link "%>
      </ul>
    </div>
  </div>
</nav>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>